FROM golang:1.27.1-alpine3.23 AS build
WORKDIR /src
RUN apk add --no-cache git
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /booking ./cmd/server

FROM alpine:3.23
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=build /booking /app/booking
COPY migrations /app/migrations
ENV PORT=8080
EXPOSE 8080
ENTRYPOINT ["/app/booking"]